db: !!binary |
  Z0FBQUFBQmw4WTdfYWQ5LTVRQklHNEVLQnBjNzUwUml6ZElLaGFvTkxyQTZPTlZDYUVNZWxodTQ4
  bEdGeXJhYW5QcXNMeGVTdzJ5cVRaQThNY3lQVHRmSUVMQnZUN2JzNmxrYXMwbTFaVFlLdUxkUXZN
  V1NPTEk9
host: !!binary |
  Z0FBQUFBQmw4WTdfdExwRFpYQWR3aVFLd3BMbjJfNUIwTXNUZ2NFSTI3b3NUcmwxWEhRSVliTnU3
  UlRNYUZEOEJiSkthbVJhZmFoSVJIdnBVX0l6c2lnczBMWlFlNmQta1Qyc0NwTExLVGhza0hhNnVB
  YlZFdDlwdjFIclhYMzRzem1Vb1IzMzFMS1UwMEx2NU1YcG5rNmN4cEp0cHVDeUlBPT0=
password: !!binary |
  Z0FBQUFBQmw4WTdfMThfY2hOVmxlZmdUQmhVb0RlalZxV1IyNGFSUlMzaEtGRmlVRi10ajN4WXEt
  MVdvSEgtUGpqZWJDMnU2STF3SzNhcG8tZHZHbGFmVVlnNkY3NW1iUFE9PQ==
user: !!binary |
  Z0FBQUFBQmw4WTdfVVFaUVZGdG9xcXA3TjM1UkVjWmhFTGc1dDl4WS1XQldqSmN0WVVISXJFcHhh
  bmUtLTVHM0YyeFhuUWlpNXd6Unc2MTFZcFYySVoyX1I4OUdFVDQ4REE9PQ==
